# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{appjam}
  s.version = "0.1.0.pre5"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eiffel Q"]
  s.date = %q{2011-04-26}
  s.default_executable = %q{appjam}
  s.description = %q{generate iphone app skeleton based on pure mvc framework}
  s.email = %q{eiffelqiu@gmail.com}
  s.executables = ["appjam"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/appjam.rb",
    "lib/appjam/generators/project.rb",
    "lib/appjam/generators/project/Classes/ContactsAppDelegate.h.tt",
    "lib/appjam/generators/project/Classes/ContactsAppDelegate.m.tt",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/core/Controller.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/core/Controller.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/core/Model.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/core/Model.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/core/View.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/core/View.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/ICommand.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/IController.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/IFacade.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/IMediator.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/IModel.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/INotification.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/INotifier.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/IObserver.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/IProxy.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/interfaces/IView.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/command/MacroCommand.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/command/MacroCommand.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/command/SimpleCommand.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/command/SimpleCommand.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/facade/Facade.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/facade/Facade.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/mediator/Mediator.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/mediator/Mediator.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/observer/Notification.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/observer/Notification.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/observer/Notifier.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/observer/Notifier.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/observer/Observer.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/observer/Observer.m",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/proxy/Proxy.h",
    "lib/appjam/generators/project/Classes/org/puremvc/objectivec/patterns/proxy/Proxy.m",
    "lib/appjam/generators/project/Classes/users/ApplicationFacade.h.tt",
    "lib/appjam/generators/project/Classes/users/ApplicationFacade.m.tt",
    "lib/appjam/generators/project/Classes/users/controller/CreateUserCommand.h.tt",
    "lib/appjam/generators/project/Classes/users/controller/CreateUserCommand.m.tt",
    "lib/appjam/generators/project/Classes/users/controller/DeleteUserCommand.h.tt",
    "lib/appjam/generators/project/Classes/users/controller/DeleteUserCommand.m.tt",
    "lib/appjam/generators/project/Classes/users/controller/GetUsersCommand.h.tt",
    "lib/appjam/generators/project/Classes/users/controller/GetUsersCommand.m.tt",
    "lib/appjam/generators/project/Classes/users/controller/StartupCommand.h.tt",
    "lib/appjam/generators/project/Classes/users/controller/StartupCommand.m.tt",
    "lib/appjam/generators/project/Classes/users/controller/UpdateUserCommand.h.tt",
    "lib/appjam/generators/project/Classes/users/controller/UpdateUserCommand.m.tt",
    "lib/appjam/generators/project/Classes/users/model/UserProxy.h.tt",
    "lib/appjam/generators/project/Classes/users/model/UserProxy.m.tt",
    "lib/appjam/generators/project/Classes/users/model/vo/UserVO.h.tt",
    "lib/appjam/generators/project/Classes/users/model/vo/UserVO.m.tt",
    "lib/appjam/generators/project/Classes/users/view/ContactsMediator.h.tt",
    "lib/appjam/generators/project/Classes/users/view/ContactsMediator.m.tt",
    "lib/appjam/generators/project/Classes/users/view/UserFormMediator.h.tt",
    "lib/appjam/generators/project/Classes/users/view/UserFormMediator.m.tt",
    "lib/appjam/generators/project/Classes/users/view/UserListMediator.h.tt",
    "lib/appjam/generators/project/Classes/users/view/UserListMediator.m.tt",
    "lib/appjam/generators/project/Classes/users/view/components/Contacts.h.tt",
    "lib/appjam/generators/project/Classes/users/view/components/Contacts.m.tt",
    "lib/appjam/generators/project/Classes/users/view/components/UserForm.h.tt",
    "lib/appjam/generators/project/Classes/users/view/components/UserForm.m.tt",
    "lib/appjam/generators/project/Classes/users/view/components/UserList.h.tt",
    "lib/appjam/generators/project/Classes/users/view/components/UserList.m.tt",
    "lib/appjam/generators/project/Contacts-Info.plist.tt",
    "lib/appjam/generators/project/Contacts.xcodeproj/eiffel.pbxuser",
    "lib/appjam/generators/project/Contacts.xcodeproj/eiffel.perspectivev3",
    "lib/appjam/generators/project/Contacts.xcodeproj/project.pbxproj",
    "lib/appjam/generators/project/Contacts_Prefix.pch.tt",
    "lib/appjam/generators/project/main.m.tt",
    "lib/appjam/generators/project/utils/NSStringWhiteSpace.h",
    "lib/appjam/generators/project/utils/NSStringWhiteSpace.m",
    "lib/appjam/generators/project/utils/UIDevice.h",
    "lib/appjam/generators/project/utils/UIDevice.m",
    "lib/appjam/generators/project/utils/URLEncodeString.h",
    "lib/appjam/generators/project/utils/URLEncodeString.m",
    "lib/appjam/version.rb"
  ]
  s.homepage = %q{http://github.com/eiffelqiu/appjam}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{an iphone app generator}
  s.test_files = [
    "spec/appjam_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

